### ISSUE TITLE
[EPIC] Query API 2.0

### ISSUE THREAD

**Issue by alex4401** [alex4401/mediawiki-extensions-DataMaps#202]
- [ ] Use ApiQueryBase.
- [ ] Support multiple titles in one request.
- [ ] Drop the arbitrary markers limit.
- [ ] `dmlimit`, `dmcontinue`
- [ ] `dmprop=markers`: Marker instances.
- [ ] `dmprop=popups`: Split popup data from instances
