### ISSUE TITLE
[EPIC] Basic visual editor functionality

### ISSUE THREAD

**Issue by alex4401** [alex4401/mediawiki-extensions-DataMaps#21]
The visual editor should allow:
* [ ] Changing a group's collectability status
* [ ] Changing whether a group is shown by default
* [ ] Adding markers to the map
* [ ] Name markers, set description, image
* [ ] Edit markers
* [ ] View coordinates regardless of map and instance settings, preferably after a click on the map

**Comment by alex4401** [comment]
This is being developed on the mainline (v0.14.0) and will be backported to v0.13.5.
