### ISSUE TITLE
[EPIC] Add an internal layer to filter markers by zoom level ranges

### ISSUE THREAD

**Issue by alex4401** [alex4401/mediawiki-extensions-DataMaps#40]
- [ ] Define the layer format (possibly property with single level or one range of levels, `zoom:3` or `zoom:3-7`)
- [ ] Ensure there is no substantial performance cost (possibly index zoom requirements separately from usual layer checks)
- [ ] Write-time validation for the layer instances
- [ ] Extend the visibility manager to handle the layer
- [ ] Have the client stream zoom layers from the API as needed
- [ ] Ensure the client does not flicker (hide previous markers only after new ones are loaded and instantiated)
- [ ] Consider putting irrelevant markers into "stasis" - take them out of active registered marker list, possibly destroy the Leaflet instances entirely
